# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
app:
  # logo (icon) of the app
  logo: "/images/logo.jpg"
  # title will appear under the avatar (optional)
  title: "Gracker App"
  # tagline will appear under the title (optional)
  tagline: "Tracking your groceries with Grocery Tracker."
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  # include_content: true
  # if inclide_subscription_form is true, the contents of the subscription.html
  # include will be added right below the content.html, if present
  inclide_subscription_form: false
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
